runtime: java17
instance_class: F2
env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  CORS_ALLOWED_ORIGINS: 'https://streetmed-frontend-l376e2l63q-uc.a.run.app'

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50