# Build stage
FROM maven:3.8.5-openjdk-17-slim as build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre-alpine
VOLUME /tmp
COPY --from=build /app/target/*.jar app.jar
# Copy the SQLite database file - needs to be copied to the runtime stage
COPY src/Backend/auth_db.sqlite /app/src/Backend/auth_db.sqlite
ENTRYPOINT ["java","-jar","/app.jar"]