name: Backend CI/CD for App Engine

on:
  push:
    branches:
      - main
    paths:
      - 'src/Backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Backend/**'
  workflow_dispatch:

env:
  PROJECT_ID: streetmedgo
  REGION: us-central1
  MYSQL_INSTANCE: streetmedgo:us-central1:streetmed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: cd src/Backend && mvn clean package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: cd src/Backend && mvn clean package -DskipTests
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Enable required APIs
      run: |
        # Enable required APIs
        gcloud services enable appengine.googleapis.com --quiet || true
        gcloud services enable cloudbuild.googleapis.com --quiet || true
        gcloud services enable sqladmin.googleapis.com --quiet || true
    
    - name: Create app.yaml
      run: |
        cd src/Backend
        mkdir -p src/main/appengine
        cat > src/main/appengine/app.yaml << 'EOF'
        runtime: java17
        instance_class: F2
        env_variables:
          SPRING_PROFILES_ACTIVE: 'prod'
          CORS_ALLOWED_ORIGINS: 'https://streetmed-frontend-l376e2l63q-uc.a.run.app'
        
        handlers:
          - url: /.*
            script: auto
            secure: always
        
        automatic_scaling:
          min_instances: 1
          max_instances: 10
          min_idle_instances: 1
          max_idle_instances: 3
          target_cpu_utilization: 0.65
          target_throughput_utilization: 0.65
          max_concurrent_requests: 50
        
        # Add Cloud SQL instance connection
        beta_settings:
          cloud_sql_instances: ${{ env.MYSQL_INSTANCE }}
        EOF
    
    - name: Deploy to App Engine
      run: |
        cd src/Backend
        mvn package appengine:deploy -DskipTests
    
    - name: Show Backend URL
      run: |
        echo "Backend URL: https://${{ env.PROJECT_ID }}.uc.r.appspot.com"
        echo "Backend successfully deployed to App Engine with Cloud SQL connectivity"
        echo "Cloud SQL Instance: ${{ env.MYSQL_INSTANCE }}"