name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/Frontend/webapp/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Frontend/webapp/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: streetmed-frontend
  REGION: us-central1
  BACKEND_URL: https://streetmed-backend-900663028964.us-central1.run.app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/Frontend/webapp/package-lock.json
    
    - name: Install dependencies and build
      run: |
        cd src/Frontend/webapp
        npm ci
        # Fix ESLint errors or disable them for CI
        echo "ESLINT_NO_DEV_ERRORS=true" > .env
        echo "CI=false" >> .env
        echo "REACT_APP_API_URL=${{ env.BACKEND_URL }}" >> .env
        npm run build
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Build and Push Docker image
      run: |
        cd src/Frontend/webapp
        gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        flags: --allow-unauthenticated

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
